name:                 UiLayoutLang
version:              0.1.0.0
visibility:           public
id:                   UiLayoutLang-0.1.0.0-inplace
key:                  UiLayoutLang-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:
    UiLayoutLang.Engine UiLayoutLang.Parser UiLayoutLang.Render
    UiLayoutLang.Types

import-dirs:
    C:\Users\darge\source\repos\UiLayoutLang\dist-newstyle\build\x86_64-windows\ghc-9.6.7\UiLayoutLang-0.1.0.0\build

library-dirs:
    C:\Users\darge\source\repos\UiLayoutLang\dist-newstyle\build\x86_64-windows\ghc-9.6.7\UiLayoutLang-0.1.0.0\build
    C:\ghcup\msys64\mingw64\lib

library-dirs-static:
    C:\Users\darge\source\repos\UiLayoutLang\dist-newstyle\build\x86_64-windows\ghc-9.6.7\UiLayoutLang-0.1.0.0\build
    C:\ghcup\msys64\mingw64\lib

dynamic-library-dirs:
    C:\Users\darge\source\repos\UiLayoutLang\dist-newstyle\build\x86_64-windows\ghc-9.6.7\UiLayoutLang-0.1.0.0\build
    C:\ghcup\msys64\mingw64\lib

data-dir:             C:\Users\darge\source\repos\UiLayoutLang\.
hs-libraries:         HSUiLayoutLang-0.1.0.0-inplace
include-dirs:         C:\ghcup\msys64\mingw64\include
depends:
    base-4.18.3.0
    megaparsec-9.8.1-5cc14b61146e47201cd9188979fce5c8600b23fe
    parser-combin_-1.3.1-3724723eecd2aa4c0c9b67e37eec38e85a98fa20
    text-2.0.2

haddock-interfaces:
    C:\Users\darge\source\repos\UiLayoutLang\dist-newstyle\build\x86_64-windows\ghc-9.6.7\UiLayoutLang-0.1.0.0\doc\html\UiLayoutLang\UiLayoutLang.haddock

haddock-html:
    C:\Users\darge\source\repos\UiLayoutLang\dist-newstyle\build\x86_64-windows\ghc-9.6.7\UiLayoutLang-0.1.0.0\doc\html\UiLayoutLang
